# Generated by Django 2.2 on 2019-06-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20190613_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('new', 'New order'), ('in review', 'in review'), ('accepted', 'accepted'), ('rejected', 'rejected'), ('shipping', 'shipping'), ('delivered', 'delivered'), ('dropped', 'dropped')], default='new', max_length=20),
        ),
    ]
